// Code generated by goa v3.10.2, DO NOT EDIT.
//
// session HTTP client CLI support package
//
// Command:
// $ goa gen cayp/api_gateway/design

package client

import (
	session "cayp/api_gateway/gen/session"
	"encoding/json"
	"fmt"
)

// BuildCreatePayload builds the payload for the session create endpoint from
// CLI flags.
func BuildCreatePayload(sessionCreateBody string) (*session.CreatePayload, error) {
	var err error
	var body CreateRequestBody
	{
		err = json.Unmarshal([]byte(sessionCreateBody), &body)
		if err != nil {
			return nil, fmt.Errorf("invalid JSON for body, \nerror: %s, \nexample of valid JSON:\n%s", err, "'{\n      \"auth\": \"eyJhbGciOiJIUz...\"\n   }'")
		}
	}
	v := &session.CreatePayload{
		Auth: body.Auth,
	}

	return v, nil
}
