// Code generated by goa v3.10.2, DO NOT EDIT.
//
// HTTP request path constructors for the session service.
//
// Command:
// $ goa gen cayp/api_gateway/design

package client

// CreateSessionPath returns the URL path to the session service create HTTP endpoint.
func CreateSessionPath() string {
	return "/1/sessions"
}
