// Code generated by goa v3.10.2, DO NOT EDIT.
//
// session HTTP client types
//
// Command:
// $ goa gen github.com/reinventingscience/ivcap-core-api/design

package client

import (
	session "github.com/reinventingscience/ivcap-core-api/gen/session"
)

// CreateRequestBody is the type of the "session" service "create" endpoint
// HTTP request body.
type CreateRequestBody struct {
	// JWT used for authentication
	Auth *string `form:"auth,omitempty" json:"auth,omitempty" xml:"auth,omitempty"`
}

// NewCreateRequestBody builds the HTTP request body from the payload of the
// "create" endpoint of the "session" service.
func NewCreateRequestBody(p *session.CreatePayload) *CreateRequestBody {
	body := &CreateRequestBody{
		Auth: p.Auth,
	}
	return body
}

// NewCreateResultOK builds a "session" service "create" endpoint result from a
// HTTP "OK" response.
func NewCreateResultOK(contentType string) *session.CreateResult {
	v := &session.CreateResult{}
	v.ContentType = contentType

	return v
}

// NewCreateInvalidCredential builds a session service create endpoint
// invalid-credential error.
func NewCreateInvalidCredential() *session.InvalidCredentialsT {
	v := &session.InvalidCredentialsT{}

	return v
}

// NewCreateNotAuthorized builds a session service create endpoint
// not-authorized error.
func NewCreateNotAuthorized() *session.UnauthorizedT {
	v := &session.UnauthorizedT{}

	return v
}
