// Code generated by goa v3.10.2, DO NOT EDIT.
//
// HTTP request path constructors for the metadata service.
//
// Command:
// $ goa gen github.com/reinventingscience/ivcap-core-api/design

package client

import (
	"fmt"
)

// ReadMetadataPath returns the URL path to the metadata service read HTTP endpoint.
func ReadMetadataPath(entityID string) string {
	return fmt.Sprintf("/1/meta/%v", entityID)
}

// AddMetadataPath returns the URL path to the metadata service add HTTP endpoint.
func AddMetadataPath(entityID string, schema string) string {
	return fmt.Sprintf("/1/meta/%v/%v", entityID, schema)
}

// RevokeMetadataPath returns the URL path to the metadata service revoke HTTP endpoint.
func RevokeMetadataPath(entityID string) string {
	return fmt.Sprintf("/1/meta/%v", entityID)
}
