// Code generated by goa v3.10.2, DO NOT EDIT.
//
// HTTP request path constructors for the artifact service.
//
// Command:
// $ goa gen cayp/api_gateway/design

package client

import (
	"fmt"
)

// ListArtifactPath returns the URL path to the artifact service list HTTP endpoint.
func ListArtifactPath() string {
	return "/1/artifacts"
}

// UploadArtifactPath returns the URL path to the artifact service upload HTTP endpoint.
func UploadArtifactPath() string {
	return "/1/artifacts"
}

// ReadArtifactPath returns the URL path to the artifact service read HTTP endpoint.
func ReadArtifactPath(id string) string {
	return fmt.Sprintf("/1/artifacts/%v", id)
}

// AddCollectionArtifactPath returns the URL path to the artifact service addCollection HTTP endpoint.
func AddCollectionArtifactPath(id string, name string) string {
	return fmt.Sprintf("/1/artifacts/%v/.collections/%v", id, name)
}

// RemoveCollectionArtifactPath returns the URL path to the artifact service removeCollection HTTP endpoint.
func RemoveCollectionArtifactPath(id string, name string) string {
	return fmt.Sprintf("/1/artifacts/%v/.collections/%v", id, name)
}

// AddMetadataArtifactPath returns the URL path to the artifact service addMetadata HTTP endpoint.
func AddMetadataArtifactPath(id string, schema string) string {
	return fmt.Sprintf("/1/artifacts/%v/.metadata/%v", id, schema)
}

// RemoveMetadataArtifactPath returns the URL path to the artifact service removeMetadata HTTP endpoint.
func RemoveMetadataArtifactPath(id string, schema string) string {
	return fmt.Sprintf("/1/artifacts/%v/.metadata/%v", id, schema)
}
