// Code generated by goa v3.10.2, DO NOT EDIT.
//
// HTTP request path constructors for the openapi service.
//
// Command:
// $ goa gen github.com/reinventingscience/ivcap-core-api/design

package client
